load("//rust:defs.bzl", "rust_proto_library")
load("@rules_rust//rust:defs.bzl", "rust_test")

proto_library(
    name = "hello_world_proto",
    srcs = ["hello_world.proto"],
)

rust_proto_library(
    name = "hello_world_rs_proto",
    deps = [":hello_world_proto"],
)

rust_test(
    name = "hello_world_test",
    srcs = ["hello_world_test.rs"],
    # TODO(b/270274576): Enable testing on arm once we have a Rust Arm toolchain.
    tags = ["not_build:arm"],
    deps = [":hello_world_rs_proto"],
)
